### ISSUE TITLE
[Question] Additional weights?

### ISSUE THREAD

**Issue by lebenna** [0xType/0xProto#12]
I absolutely love this font, great work. Do you have plans for additional weights and italics and/or obliques?

**Comment by masaakim** [comment]
@lebenna Thank you for using 0xProto!

At the moment, I don't plan to add any additional weights. Please check https://github.com/0xType/0xProto/issues/8 as well. 

However, I believe that italics/obliques should be included because text editors, like VSCode, allow you to specify italic/oblique fonts for reserved words in programming languages. This can significantly enhance legibility when going through source code.
