### ISSUE TITLE
[Feature request]: A more curly brace

### ISSUE THREAD

**Issue by sonulohani** [0xType/0xProto#24]
### What feature are you proposing?

I really love this font. Its very readable. The only issue I have with this font is the curly brace which is somewhat flat. 
![image](https://github.com/MonoLisaFont/feedback/assets/2958681/7797a1d1-e0f9-407e-801e-4d3ba95e16a2)

I really like input mono curly brace
![image](https://github.com/MonoLisaFont/feedback/assets/2958681/4f1d3e30-1f9d-4bfa-9872-bec783058cdb)

This is from intel one mono
![image](https://github.com/MonoLisaFont/feedback/assets/2958681/5c04be53-7f72-47e7-b02f-fc4c3b7c2bae)

Is it possible to introduce one more variant of curly brace in this font. It would be very lovely to have this. 

Thanks

**Comment by masaakim** [comment]
At 0xProto, legibility is our top priority, which is why I regularly fine-tune the characters.

While it's crucial for each character to be easily distinguishable, it's equally vital for all the characters to maintain a consistent look within the font. So, while I'm not sure if the adjustments will be as pronounced as in the screenshot example, I'll strive to enhance its identifiability while preserving the distinctive 0xProto style.

**Comment by sonulohani** [comment]
No problem. Thanks for the explanation.

**Comment by masaakim** [comment]
Hi, @sonulohani 

I've adjusted the shape of the curly braces in https://github.com/0xType/0xProto/pull/18 and just released [v1.300](https://github.com/0xType/0xProto/releases/tag/1.300).
