### ISSUE TITLE
Support  box-drawing characters

### ISSUE THREAD

**Issue by forrcaho** [0xType/0xProto#6]
When using 0xProto to edit some keyboard code that uses box characters, I noticed that the box characters don't line up with the text:

<img width="1034" alt="box_character_example_0xProto" src="https://github.com/0xType/0xProto/assets/492742/016831fa-6faf-44bf-8533-b08eb9cbb96b">

For reference, here is the same code rendered with Hack:

<img width="1003" alt="box_character_example_Hack" src="https://github.com/0xType/0xProto/assets/492742/829c9e5d-f661-4e61-887b-e90b3fe349b3">

This is in VSCode on Win11.

**Comment by masaakim** [comment]
@forrcaho 
Thank you for using 0xProto!

> the box characters don't line up with the text

This is because box-drawing characters do not currently exist in 0xProto.
(FYI: All glyphs in the current version https://github.com/0xType/0xProto/tree/main/0xProto-Regular.ufo/glyphs )

I think this is an essential feature for a programming font and will definitely support it in the near future.

**Comment by masaakim** [comment]
I'm in progress. 
For now, I have created 128 symbols from 2500 to 257F in Unicode.

<img width="2227" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/e132c01c-c10a-4b0d-bf7d-6db592af60c8">

**Comment by masaakim** [comment]
Added box-drawing characters in https://github.com/0xType/0xProto/pull/17 . This will be included in the next release build.

**Comment by masaakim** [comment]
I've just released v1.200! https://github.com/0xType/0xProto/releases/tag/1.200
