### ISSUE TITLE
Single font weight on IntelliJ IDEA 

### ISSUE THREAD

**Issue by nobeh** [0xType/0xProto#70]
Thanks for making 0xProto.

I just tried 0xProto on IntelliJ IDEA. Maybe I am missing something but there's only one weight `Regular` which is displayed/listed by IDE. Screenshot attached.

Environment:

```
IntelliJ IDEA 2024.1.1 RC (Ultimate Edition)
Build #IU-241.15989.69, built on April 18, 2024

Runtime version: 17.0.10+1-b1207.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
Metal Rendering is ON
```

Could it be related that I installed the font using `brew` and the installation only involves OTF font files?

<img width="953" alt="image" src="https://github.com/0xType/0xProto/assets/1003027/e8ea74e2-7225-4df5-ad50-1be5cdc43b3a">

**Comment by nobeh** [comment]
I just tried the distribution archive as well:

```shell
$ tar tvf 0xProto_1_603.zip
drwxr-xr-x  0 501    20          0 Mar 18 03:05 fonts/
-rw-r--r--  0 501    20      71960 Mar 18 03:05 fonts/0xProto-Regular.ttf
-rw-r--r--  0 501    20      55192 Mar 18 03:05 fonts/0xProto-Regular.otf
-rw-r--r--  0 501    20      24296 Mar 18 03:05 fonts/0xProto-Regular.woff2
```

It seems that only Regular weight is shipped.

**Comment by masaakim** [comment]
Hi @nobeh , thank you for using and detailed feedback!

At the moment, I don't plan to add any additional weights. I feel the current characters shape of 0xProto offers optimal legibility and readability for coding in a text editor.

In 0xProto, the Regular weight is a tad thicker compared to similar weights in other programming fonts. This subtle change allows for more generous syntax highlighting, making character identification a breeze. Therefore, I believe it is difficult to provide Bold weight while maintaining legibility.

However, I believe that italics/obliques (will be released soon! https://github.com/0xType/0xProto/pull/66 ) should be included because text editors, like VSCode, allow you to specify italic/oblique fonts for reserved words in programming languages. This can significantly enhance legibility when going through source code.
