### ISSUE TITLE
Dotted zero

### ISSUE THREAD

**Issue by arjpar** [0xType/0xProto#80]
Could it be possible to have a dotted zero by default or exposed through a character variant (cv)? If default, a slashed zero could be a character variant.

**Comment by matype** [comment]
0xProto is a font focused on the legibility of characters. I don't think dotted zero or slashed zero has anything to do with legibility.
Since 0xProto is my personal project, I am making this up in my opinion as to whether I like or dislike the letterforms, which has nothing to do with legibility.
I may change my mind in the future, but I have no plans to add dotted zero.

FYI: https://github.com/0xType/0xProto/issues/4
