### ISSUE TITLE
'name' table usability error when installing using Font Book on macOS

### ISSUE THREAD

**Issue by joshlawton** [0xType/0xProto#84]
When installing the 2.100 version of the OTF and TTF fonts on macOS 12.7.6, Font Book complains of 'name' table usability errors. (Neither font was previously installed.)

Steps to reproduce:

1. Download the latest release (2.100) from GitHub as a ZIP file.
2. Extract files.
3. In Finder, highlight the font(s) to install, right-click on it (them) and select **Open With** ➡️  **Font Book**.
4. Font Book shows a preview of the highlighted font(s). Click **Install**.
5. Font Book starts to validate the font(s) and raises an error.

<img width="717" alt="Screenshot showing errors installing the OTF font via Font Book" src="https://github.com/user-attachments/assets/e64efb88-66d1-4649-bc5f-d7e8d72928ba">

<img width="708" alt="Screenshot showing errors installing the TTF font via Font Book" src="https://github.com/user-attachments/assets/26b3db91-bab0-4aa0-a6c0-439374f745e1">

**Comment by matype** [comment]
Thank you for your feedback. I'll investigate the cause.

**Comment by matype** [comment]
@joshlawton Fixed in https://github.com/0xType/0xProto/pull/83 and just released [v2.200](https://github.com/0xType/0xProto/releases/tag/2.200)!

I've confirmed that this validation caution has been fixed in v2.200.

<img width="752" alt="image" src="https://github.com/user-attachments/assets/3de5a270-42ab-4eb2-a041-af603d63cdfe">

**Comment by joshlawton** [comment]
I installed 2.200 with no errors on my laptop. Thank you very much for the bug fix and making this wonderful font 👍🏼
